package uk.nhs.adaptors.pss.translator.util;


import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.util.HashMap;
import java.util.Map;

@Component
public class MeasurementUnitsUtil {

    private static final Map<String, String> units = new HashMap<>();

    @PostConstruct
    public void createUnits() {
        units.put("10.L/min","10 liter per minute");
        units.put("10.L/(min.m2)","10 liter per minute per square meter");
        units.put("10.uN.s/(cm5.m2)","10 micronewton second per centimeter to the fifth power per square meter");
        units.put("10*4/uL","10 thousand per microliter");
        units.put("10*8","100 million ");
        units.put("24.h","24 hour");
        units.put("{absorbance}","absorbance");
        units.put("{activity}","activity");
        units.put("[AU]","allergy unit");
        units.put("{AHF'U}","American Hospital Formulary unit");
        units.put("A","ampere");
        units.put("A/m","ampere per meter");
        units.put("[arb'U]","arbitrary unit");
        units.put("[arb'U]/mL","arbitrary unit per milliliter");
        units.put("{ARU}","aspirin response unit");
        units.put("atm","atmosphere");
        units.put("ag/{cell}","attogram per cell");
        units.put("bar","bar");
        units.put("Bq","Becquerel");
        units.put("[beth'U]","Bethesda unit");
        units.put("10*9/L","billion per liter");
        units.put("10*9/uL","billion per microliter");
        units.put("10*9/mL","billion per milliliter");
        units.put("{binding_index}","binding index");
        units.put("[bdsk'U]","Bodansky unit");
        units.put("{breaths}/min","breaths per minute");
        units.put("{CAG_repeats}","CAG trinucleotide repeats");
        units.put("cal","calorie");
        units.put("{cells}","cells");
        units.put("{cells}/[HPF]","cells per high power field");
        units.put("{cells}/uL","cells per microliter");
        units.put("cg","centigram");
        units.put("cL","centiliter");
        units.put("cm","centimeter");
        units.put("cm[Hg]","centimeter of mercury");
        units.put("cm[H2O]","centimeter of water");
        units.put("cm[H2O]/L/s","centimeter of water per liter per second");
        units.put("cm[H2O]/s/m","centimeter of water per second per meter");
        units.put("cm/s","centimeter per second");
        units.put("cP","centipoise");
        units.put("cSt","centistoke");
        units.put("{delta_OD}","change in (delta) optical density");
        units.put("{clock_time}","clock time e.g 12:30PM");
        units.put("[CFU]","colony forming unit");
        units.put("[CFU]/L","colony forming unit per liter");
        units.put("[CFU]/mL","colony forming unit per milliliter");
        units.put("{CAE'U}","complement activity enzyme unit");
        units.put("{CH100'U}","complement CH100 unit");
        units.put("{copies}","copies");
        units.put("{copies}/ug","copies per microgram");
        units.put("{copies}/mL","copies per milliliter");
        units.put("{count}","count");
        units.put("{CPM}","counts per minute");
        units.put("{CPM}/10*3{cell}","counts per minute per thousand cells");
        units.put("cm3","cubic centimeter");
        units.put("[cin_i]","cubic inch (international)");
        units.put("m3/s","cubic meter per second");
        units.put("{Ct_value}","Cycle threshold value");
        units.put("d","day");
        units.put("d/(7.d)","day per 7 day");
        units.put("d/wk","days per week");
        units.put("dB","decibel");
        units.put("dg","decigram");
        units.put("dL","deciliter");
        units.put("dm","decimeter");
        units.put("deg","degree (plane angle)");
        units.put("Cel","degree Celsius");
        units.put("[degF]","degree Fahrenheit");
        units.put("K","degree Kelvin");
        units.put("K/W","degree Kelvin per Watt");
        units.put("deg/s","degree per second");
        units.put("daL/min","dekaliter per minute");
        units.put("daL/min/m2","dekaliter per minute per square meter");
        units.put("{dilution}","dilution");
        units.put("[diop]","diopter");
        units.put("[dr_av]","dram  (US and British)");
        units.put("[drp]","drop (1/12 milliliter)");
        units.put("dyn.s/cm","dyne second per centimeter");
        units.put("dyn.s/(cm.m2)","dyne second per centimeter per square meter");
        units.put("{Ehrlich'U}","Ehrlich unit");
        units.put("{Ehrlich'U}/100.g","Ehrlich unit per 100 gram");
        units.put("{Ehrlich'U}/(2.h)","Ehrlich unit per 2 hour");
        units.put("{Ehrlich'U}/d","Ehrlich unit per day");
        units.put("{Ehrlich'U}/dL","Ehrlich unit per deciliter");
        units.put("{EIA_index}","EIA index");
        units.put("{EIA_titer}","EIA titer");
        units.put("{EIA'U}","EIA unit");
        units.put("{EIA'U}/U","EIA unit per enzyme unit");
        units.put("{EV}","EIA value");
        units.put("eV","electron Volt");
        units.put("{ELISA'U}","ELISA unit");
        units.put("U","enzyme unit");
        units.put("U/10","enzyme unit per 10");
        units.put("U/10*10","enzyme unit per 10 billion");
        units.put("U/10*10{cells}","enzyme unit per 10 billion cells");
        units.put("U/(10.g){feces}","enzyme unit per 10 gram of feces");
        units.put("U/(12.h)","enzyme unit per 12 hour");
        units.put("U/(2.h)","enzyme unit per 2 hour");
        units.put("U/(24.h)","enzyme unit per 24 hour");
        units.put("U/10*9","enzyme unit per billion");
        units.put("U/d","enzyme unit per day");
        units.put("U/dL","enzyme unit per deciliter");
        units.put("U/g","enzyme unit per gram");
        units.put("U/g{creat}","enzyme unit per gram of creatinine");
        units.put("U/g{Hb}","enzyme unit per gram of hemoglobin");
        units.put("U/g{protein}","enzyme unit per gram of protein");
        units.put("U/h","enzyme unit per hour");
        units.put("U/kg{Hb}","enzyme unit per kilogram of hemoglobin");
        units.put("U/L","enzyme unit per liter");
        units.put("U{25Cel}/L","enzyme unit per liter at 25 deg Celsius ");
        units.put("U{37Cel}/L","enzyme unit per liter at 37 deg Celsius");
        units.put("U/mL","enzyme unit per milliliter");
        units.put("U/mL{RBCs}","enzyme unit per milliliter of red blood cells");
        units.put("U/mmol{creat}","enzyme unit per millimole of creatinine");
        units.put("U/10*6","enzyme unit per million");
        units.put("U/min","enzyme unit per minute");
        units.put("U/s","enzyme unit per second");
        units.put("U/10*12","enzyme unit per trillion");
        units.put("U/10*12{RBCs}","enzyme unit per trillion red blood cells");
        units.put("eq","equivalent");
        units.put("eq/L","equivalent per liter");
        units.put("eq/umol","equivalent per micromole");
        units.put("eq/mL","equivalent per milliliter");
        units.put("eq/mmol","equivalent per millimole");
        units.put("erg","erg");
        units.put("F","Farad");
        units.put("[ft_us]/[ft_us]","feet (US) per feet (US)");
        units.put("fg","femtogram");
        units.put("fL","femtoliter");
        units.put("fm","femtometer");
        units.put("fmol","femtomole");
        units.put("fmol/g","femtomole per gram");
        units.put("fmol/L","femtomole per liter");
        units.put("fmol/mg","femtomole per milligram");
        units.put("fmol/mg{cyt_prot}","femtomole per milligram of cytosol protein");
        units.put("fmol/mg{prot}","femtomole per milligram of protein");
        units.put("fmol/mL","femtomole per milliliter");
        units.put("[foz_us]","fluid ounce (US)");
        units.put("{FIU}","fluorescent intensity unit");
        units.put("[ft_i]","foot (international)");
        units.put("{fraction}","fraction");
        units.put("[Ch]","French (catheter gauge) ");
        units.put("{GAA_repeats}","GAA trinucleotide repeats");
        units.put("[gal_us]","gallon (US)");
        units.put("{genomes}/mL","genomes per milliliter");
        units.put("{Globules}/[HPF]","globules (drops)  per high power field");
        units.put("g","gram");
        units.put("g.m","gram meter");
        units.put("g.m/{beat}","gram meter per heart beat ");
        units.put("g{creat}","gram of creatinine");
        units.put("g{Hb}","gram of hemoglobin");
        units.put("g{total_nit}","gram of total nitrogen");
        units.put("g{total_prot}","gram of total protein");
        units.put("g{wet_tissue}","gram of wet tissue");
        units.put("g/kg/(8.h)","gram per  kilogram per 8 hour ");
        units.put("g/(100.g)","gram per 100 gram");
        units.put("g/(12.h)","gram per 12 hour");
        units.put("g/(24.h)","gram per 24 hour");
        units.put("g/(3.d)","gram per 3 days");
        units.put("g/(4.h)","gram per 4 hour");
        units.put("g/(48.h)","gram per 48 hour");
        units.put("g/(5.h)","gram per 5 hour");
        units.put("g/(6.h)","gram per 6 hour");
        units.put("g/(72.h)","gram per 72 hour");
        units.put("g/(8.h){shift}","gram per 8 hour shift");
        units.put("g/cm3","gram per cubic centimeter");
        units.put("g/d","gram per day");
        units.put("g/dL","gram per deciliter");
        units.put("g/g","gram per gram");
        units.put("g/g{creat}","gram per gram of creatinine");
        units.put("g/g{globulin}","gram per gram of globulin");
        units.put("g/g{tissue}","gram per gram of tissue");
        units.put("g/h","gram per hour");
        units.put("g/h/m2","gram per hour per square meter");
        units.put("g/kg","gram per kilogram");
        units.put("g/kg/(8.h){shift}","gram per kilogram per 8 hour shift");
        units.put("g/kg/d","gram per kilogram per day");
        units.put("g/kg/h","gram per kilogram per hour");
        units.put("g/kg/min","gram per kilogram per minute");
        units.put("g/L","gram per liter");
        units.put("g/mg","gram per milligram");
        units.put("g/mL","gram per milliliter");
        units.put("g/mmol","gram per millimole");
        units.put("g/min","gram per minute");
        units.put("g/mol{creat}","gram per mole of creatinine");
        units.put("g/{specimen}","gram per specimen");
        units.put("g/cm2","gram per square centimeter");
        units.put("g/m2","gram per square meter");
        units.put("g/{total_output}","gram per total output");
        units.put("g/{total_weight}","gram per total weight");
        units.put("Gy","Gray");
        units.put("{beats}/min","heart beats per minute");
        units.put("H","Henry");
        units.put("Hz","Hertz");
        units.put("[HPF]","high power field");
        units.put("h","hour");
        units.put("h/d","hour per day");
        units.put("h/wk","hour per week");
        units.put("[APL'U]/mL","IgA anticardiolipin unit per milliliter**");
        units.put("[APL'U]","IgA anticardiolipin unit**");
        units.put("{APS'U}","IgA antiphosphatidylserine unit ");
        units.put("[GPL'U]/mL","IgG anticardiolipin unit per milliliter**");
        units.put("[GPL'U]","IgG anticardiolipin unit**");
        units.put("{GPS'U}","IgG antiphosphatidylserine unit");
        units.put("[MPL'U]/mL","IgM anticardiolipin unit per milliliter**");
        units.put("[MPL'U]","IgM anticardiolipin unit**");
        units.put("{MPS'U}","IgM antiphosphatidylserine unit");
        units.put("{MPS'U}/mL","IgM antiphosphatidylserine unit per milliliter");
        units.put("{ImmuneComplex'U}","immune complex unit");
        units.put("{ISR}","immune status ratio");
        units.put("{IFA_index}","immunofluorescence assay index");
        units.put("{IFA_titer}","Immunofluorescence assay titer");
        units.put("[in_i]","inch (international)");
        units.put("[in_i'H2O]","inch (international) of water");
        units.put("[in_us]","inches (US)");
        units.put("{index_val}","index value");
        units.put("{index}","index value");
        units.put("{HA_titer}","influenza hemagglutination titer");
        units.put("{INR}","international normalized ratio");
        units.put("[IU]","international unit");
        units.put("[IU]/(2.h)","international unit per 2 hour");
        units.put("[IU]/(24.h)","international unit per 24 hour");
        units.put("[IU]/10*9{RBCs}","international unit per billion red blood cells");
        units.put("[IU]/d","international unit per day");
        units.put("[IU]/dL","international unit per deciliter");
        units.put("[IU]/g","international unit per gram");
        units.put("[IU]/g{Hb}","international unit per gram of hemoglobin");
        units.put("[IU]/h","international unit per hour");
        units.put("[IU]/kg","international unit per kilogram");
        units.put("[IU]/kg/d","international unit per kilogram per day");
        units.put("[IU]/L","international unit per liter");
        units.put("[IU]/L{37Cel}","international unit per liter at 37 degrees Celsius");
        units.put("[IU]/mg{creat}","international unit per milligram of creatinine");
        units.put("[IU]/mL","international unit per milliliter");
        units.put("[IU]/min","international unit per minute");
        units.put("J","joule");
        units.put("J/L","joule per liter");
        units.put("{JDF'U}","Juvenile Diabetes Foundation unit");
        units.put("{JDF'U}/L","Juvenile Diabetes Foundation unit per liter");
        units.put("{KCT'U}","kaolin clotting time");
        units.put("kat","katal");
        units.put("kat/kg","katal per kilogram");
        units.put("kat/L","katal per liter");
        units.put("kU","kilo enzyme unit");
        units.put("kU/g","kilo enzyme unit per gram");
        units.put("kU/L","kilo enzyme unit per liter");
        units.put("kU/L{class}","kilo enzyme unit per liter class");
        units.put("kU/mL","kilo enzyme unit per milliliter");
        units.put("k[IU]/L","kilo international unit per liter");
        units.put("k[IU]/mL","kilo international unit per milliliter");
        units.put("kcal","kilocalorie");
        units.put("kcal/(24.h)","kilocalorie per 24 hour");
        units.put("kcal/d","kilocalorie per day");
        units.put("kcal/h","kilocalorie per hour");
        units.put("kcal/kg/(24.h)","kilocalorie per kilogram per 24 hour");
        units.put("kcal/[oz_av]","kilocalorie per ounce (US & British)");
        units.put("kg","kilogram");
        units.put("kg.m/s","kilogram meter per second");
        units.put("kg/m3","kilogram per cubic meter");
        units.put("kg/h","kilogram per hour");
        units.put("kg/L","kilogram per liter");
        units.put("kg/min","kilogram per minute");
        units.put("kg/mol","kilogram per mole");
        units.put("kg/s","kilogram per second");
        units.put("kg/(s.m2)","kilogram per second per square meter");
        units.put("kg/m2","kilogram per square meter");
        units.put("kL","kiloliter");
        units.put("km","kilometer");
        units.put("kPa","kilopascal");
        units.put("ks","kilosecond");
        units.put("[ka'U]","King Armstrong unit");
        units.put("{KRONU'U}/mL","Kronus unit per milliliter");
        units.put("[knk'U]","Kunkel unit");
        units.put("L","liter");
        units.put("L/(24.h)","liter per 24 hour");
        units.put("L/(8.h)","liter per 8 hour");
        units.put("L/d","liter per day");
        units.put("L/h","liter per hour");
        units.put("L/kg","liter per kilogram");
        units.put("L/L","liter per liter");
        units.put("L/min","liter per minute");
        units.put("L/min/m2","liter per minute per sqaure meter");
        units.put("L/(min.m2)","liter per minute per square meter");
        units.put("L/s","liter per second");
        units.put("L/s/s2","liter per second per square second");
        units.put("{Log_copies}/mL","log (base 10) copies per milliliter");
        units.put("{Log_IU}","log (base 10) international unit");
        units.put("{Log_IU}/mL","log (base 10) international unit per milliliter");
        units.put("{Log}","log base 10");
        units.put("[LPF]","low power field");
        units.put("lm","lumen");
        units.put("lm.m2","lumen square meter");
        units.put("{Lyme_index_value}","Lyme index value");
        units.put("[mclg'U]","Maclagan unit");
        units.put("Ms","megasecond");
        units.put("[MET].min/wk","metabolic equivalent minute per week");
        units.put("m","meter");
        units.put("m/s","meter per second");
        units.put("m/s2","meter per square second");
        units.put("t","metric ton");
        units.put("uU/g","micro enzyme unit per gram");
        units.put("uU/L","micro enzyme unit per liter");
        units.put("uU/mL","micro enzyme unit per milliliter");
        units.put("u[IU]","micro international unit");
        units.put("u[IU]/mL","micro international unit per milliliter");
        units.put("ueq","microequivalent");
        units.put("ueq/L","microequivalent per liter");
        units.put("ueq/mL","microequivalent per milliliter");
        units.put("ug","microgram");
        units.put("ug/g{feces}","microgram  per gram of feces");
        units.put("ug{FEU}/mL","microgram fibrinogen equivalent unit per milliliter");
        units.put("ug/(100.g)","microgram per 100 gram");
        units.put("ug/(24.h)","microgram per 24 hour");
        units.put("ug/(8.h)","microgram per 8 hour");
        units.put("ug/m3","microgram per cubic meter");
        units.put("ug/d","microgram per day");
        units.put("ug/dL","microgram per deciliter");
        units.put("ug/dL{RBCs}","microgram per deciliter of red blood cells");
        units.put("ug/g","microgram per gram");
        units.put("ug/g{creat}","microgram per gram of creatinine");
        units.put("ug/g{dry_tissue}","microgram per gram of dry tissue");
        units.put("ug/g{dry_wt}","microgram per gram of dry weight");
        units.put("ug/g{hair}","microgram per gram of hair");
        units.put("ug/g{Hb}","microgram per gram of hemoglobin");
        units.put("ug/g{tissue}","microgram per gram of tissue");
        units.put("ug/h","microgram per hour");
        units.put("ug/kg","microgram per kilogram");
        units.put("ug/kg/(8.h)","microgram per kilogram per 8 hour");
        units.put("ug/kg/d","microgram per kilogram per day");
        units.put("ug/kg/h","microgram per kilogram per hour");
        units.put("ug/kg/min","microgram per kilogram per minute");
        units.put("ug/L","microgram per liter");
        units.put("ug/L{RBCs}","microgram per liter of red blood cells");
        units.put("ug/L/(24.h)","microgram per liter per 24 hour");
        units.put("ug/mg","microgram per milligram");
        units.put("ug/mg{creat}","microgram per milligram of creatinine");
        units.put("ug/mL","microgram per milliliter");
        units.put("ug/mL{class}","microgram per milliliter class");
        units.put("ug/mL{eqv}","microgram per milliliter equivalent");
        units.put("ug/mmol","microgram per millimole");
        units.put("ug/mmol{creat}","microgram per millimole of creatinine");
        units.put("ug/min","microgram per minute");
        units.put("ug/ng","microgram per nanogram");
        units.put("ug/{specimen}","microgram per specimen");
        units.put("ug/[sft_i]","microgram per square foot (international)");
        units.put("ug/m2","microgram per square meter");
        units.put("u[IU]/L","microinternational unit per liter");
        units.put("ukat","microkatal");
        units.put("uL","microliter");
        units.put("uL/(2.h)","microliter per 2 hour");
        units.put("uL/h","microliter per hour");
        units.put("um","micrometer");
        units.put("umol","micromole");
        units.put("umol{BCE}/mol","micromole bone collagen equivalent per mole");
        units.put("umol/(2.h)","micromole per 2 hour");
        units.put("umol/(24.h)","micromole per 24 hour");
        units.put("umol/(8.h)","micromole per 8 hour");
        units.put("umol/d","micromole per day");
        units.put("umol/dL","micromole per deciliter");
        units.put("umol/dL{GF}","micromole per deciliter of glomerular filtrate");
        units.put("umol/g","micromole per gram");
        units.put("umol/g{creat}","micromole per gram of creatinine");
        units.put("umol/g{Hb}","micromole per gram of hemoglobin");
        units.put("umol/h","micromole per hour");
        units.put("umol/kg","micromole per kilogram");
        units.put("umol/kg{feces}","micromole per kilogram of feces");
        units.put("umol/L","micromole per liter");
        units.put("umol/L{RBCs}","micromole per liter of red blood cells");
        units.put("umol/L/h","micromole per liter per hour");
        units.put("umol/umol","micromole per micromole");
        units.put("umol/umol{creat}","micromole per micromole of creatinine");
        units.put("umol/mg","micromole per milligram");
        units.put("umol/mg{creat}","micromole per milligram of creatinine");
        units.put("umol/mL","micromole per milliliter");
        units.put("umol/mL/min","micromole per milliliter per minute");
        units.put("umol/mmol","micromole per millimole");
        units.put("umol/mmol{creat}","micromole per millimole of creatinine");
        units.put("umol/10*6{RBC}","micromole per million red blood cell");
        units.put("umol/min","micromole per minute");
        units.put("umol/min/g","micromole per minute per gram");
        units.put("umol/min/g{mucosa}","micromole per minute per gram of mucosa");
        units.put("umol/min/g{prot}","micromole per minute per gram of protein");
        units.put("umol/min/L","micromole per minute per liter");
        units.put("umol/mol","micromole per mole");
        units.put("umol/mol{creat}","micromole per mole of creatinine");
        units.put("umol/mol{Hb}","micromole per mole of hemoglobin");
        units.put("um/s","microns per second");
        units.put("uOhm","microOhm");
        units.put("us","microsecond");
        units.put("uV","microvolt");
        units.put("[mi_i]","mile (international)");
        units.put("mU/g","milli  enzyme unit per gram");
        units.put("mU/mL","milli  enzyme unit per milliliter");
        units.put("mU/mL/min","milli  enzyme unit per milliliter per minute");
        units.put("mU/mmol{creat}","milli  enzyme unit per millimole of creatinine");
        units.put("mU/mmol{RBCs}","milli  enzyme unit per millimole of red blood cells");
        units.put("m[IU]/mL","milli  international unit per milliliter");
        units.put("mU/g{Hb}","milli enzyme unit per gram of hemoglobin");
        units.put("mU/g{prot}","milli enzyme unit per gram of protein");
        units.put("mU/L","milli enzyme unit per liter");
        units.put("mU/mg","milli enzyme unit per milligram");
        units.put("mU/mg{creat}","milli enzyme unit per milligram of creatinine");
        units.put("m[IU]/L","milli international unit per liter");
        units.put("mA","milliampere");
        units.put("mbar","millibar");
        units.put("mbar/L/s","millibar per liter per second");
        units.put("mbar.s/L","millibar second per liter");
        units.put("meq","milliequivalent");
        units.put("meq/(2.h)","milliequivalent per 2 hour");
        units.put("meq/(24.h)","milliequivalent per 24 hour");
        units.put("meq/(8.h)","milliequivalent per 8 hour");
        units.put("meq/d","milliequivalent per day");
        units.put("meq/dL","milliequivalent per deciliter");
        units.put("meq/g","milliequivalent per gram");
        units.put("meq/g{creat}","milliequivalent per gram of creatinine");
        units.put("meq/h","milliequivalent per hour");
        units.put("meq/kg","milliequivalent per kilogram");
        units.put("meq/kg/h","milliequivalent per kilogram per hour");
        units.put("meq/L","milliequivalent per liter");
        units.put("meq/mL","milliequivalent per milliliter");
        units.put("meq/min","milliequivalent per minute");
        units.put("meq/{specimen}","milliequivalent per specimen");
        units.put("meq/m2","milliequivalent per square meter");
        units.put("meq/{total_volume}","milliequivalent per total volume");
        units.put("mg","milligram");
        units.put("mg{FEU}/L","milligram fibrinogen equivalent unit per liter");
        units.put("mg/(10.h)","milligram per 10 hour");
        units.put("mg/(12.h)","milligram per 12 hour");
        units.put("mg/(2.h)","milligram per 2 hour");
        units.put("mg/(24.h)","milligram per 24 hour");
        units.put("mg/(6.h)","milligram per 6 hour");
        units.put("mg/(72.h)","milligram per 72 hour");
        units.put("mg/(8.h)","milligram per 8 hour");
        units.put("mg/{collection}","milligram per collection");
        units.put("mg/m3","milligram per cubic meter");
        units.put("mg/d","milligram per day");
        units.put("mg/d/{1.73_m2}","milligram per day per 1.73 square meter");
        units.put("mg/dL","milligram per deciliter");
        units.put("mg/dL{RBCs}","milligram per deciliter of red blood cells");
        units.put("mg/g","milligram per gram");
        units.put("mg/g{creat}","milligram per gram of creatinine");
        units.put("mg/g{dry_tissue}","milligram per gram of dry tissue");
        units.put("mg/g{feces}","milligram per gram of feces");
        units.put("mg/g{tissue}","milligram per gram of tissue");
        units.put("mg/g{wet_tissue}","milligram per gram of wet tissue");
        units.put("mg/h","milligram per hour");
        units.put("mg/kg","milligram per kilogram");
        units.put("mg/kg/(8.h)","milligram per kilogram per 8 hour");
        units.put("mg/kg/d","milligram per kilogram per day");
        units.put("mg/kg/h","milligram per kilogram per hour");
        units.put("mg/kg/min","milligram per kilogram per minute");
        units.put("mg/L","milligram per liter");
        units.put("mg/L{RBCs}","milligram per liter of red blood cells");
        units.put("mg/mg","milligram per milligram");
        units.put("mg/mg{creat}","milligram per milligram of creatinine");
        units.put("mg/mL","milligram per milliliter");
        units.put("mg/mmol","milligram per millimole");
        units.put("mg/mmol{creat}","milligram per millimole of creatinine");
        units.put("mg/min","milligram per minute");
        units.put("mg/{specimen}","milligram per specimen");
        units.put("mg/m2","milligram per square meter");
        units.put("mg/{total_output}","milligram per total output");
        units.put("mg/{total_volume}","milligram per total volume");
        units.put("mg/wk","milligram per week");
        units.put("mL","milliliter");
        units.put("mL{fetal_RBCs}","milliliter of fetal red blood cells");
        units.put("mL/(10.h)","milliliter per 10 hour");
        units.put("mL/(12.h)","milliliter per 12 hour");
        units.put("mL/(2.h)","milliliter per 2 hour");
        units.put("mL/(24.h)","milliliter per 24 hour");
        units.put("mL/(4.h)","milliliter per 4 hour");
        units.put("mL/(5.h)","milliliter per 5 hour");
        units.put("mL/(6.h)","milliliter per 6 hour");
        units.put("mL/(72.h)","milliliter per 72 hour");
        units.put("mL/(8.h)","milliliter per 8 hour");
        units.put("mL/(8.h)/kg","milliliter per 8 hour per kilogram");
        units.put("mL/cm[H2O]","milliliter per centimeter of water");
        units.put("mL/d","milliliter per day");
        units.put("mL/dL","milliliter per deciliter");
        units.put("mL/{beat}","milliliter per heart beat");
        units.put("mL/{beat}/m2","milliliter per heart beat per  square meter");
        units.put("mL/h","milliliter per hour");
        units.put("mL/kg","milliliter per kilogram");
        units.put("mL/kg/(8.h)","milliliter per kilogram per 8 hour");
        units.put("mL/kg/d","milliliter per kilogram per day");
        units.put("mL/kg/h","milliliter per kilogram per hour");
        units.put("mL/kg/min","milliliter per kilogram per minute");
        units.put("mL/mbar","milliliter per millibar");
        units.put("mL/mm","milliliter per millimeter");
        units.put("mL/min","milliliter per minute");
        units.put("mL/min/{1.73_m2}","milliliter per minute per 1.73 square meter");
        units.put("mL/min/m2","milliliter per minute per square meter");
        units.put("mL/s","milliliter per second");
        units.put("mL/[sin_i]","milliliter per square inch (international)");
        units.put("mL/m2","milliliter per square meter");
        units.put("mm","millimeter");
        units.put("mm[Hg]","millimeter of mercury");
        units.put("mm[H2O]","millimeter of water");
        units.put("mm/h","millimeter per hour");
        units.put("mm/min","millimeter per minute");
        units.put("mmol","millimole");
        units.put("mmol/(12.h)","millimole per 12 hour");
        units.put("mmol/(2.h)","millimole per 2 hour");
        units.put("mmol/(24.h)","millimole per 24 hour");
        units.put("mmol/(5.h)","millimole per 5 hour");
        units.put("mmol/(6.h)","millimole per 6 hour");
        units.put("mmol/(8.h)","millimole per 8 hour");
        units.put("mmol/d","millimole per day");
        units.put("mmol/dL","millimole per deciliter");
        units.put("mmol/{ejaculate}","millimole per ejaculate");
        units.put("mmol/g","millimole per gram");
        units.put("mmol/g{creat}","millimole per gram of creatinine");
        units.put("mmol/h","millimole per hour");
        units.put("mmol/h/mg{Hb}","millimole per hour per milligram of hemoglobin");
        units.put("mmol/h/mg{prot}","millimole per hour per milligram of protein");
        units.put("mmol/kg","millimole per kilogram");
        units.put("mmol/kg/(8.h)","millimole per kilogram per 8 hour");
        units.put("mmol/kg/d","millimole per kilogram per day");
        units.put("mmol/kg/h","millimole per kilogram per hour");
        units.put("mmol/kg/min","millimole per kilogram per minute");
        units.put("mmol/L","millimole per liter");
        units.put("mmol/L{RBCs}","millimole per liter of red blood cells");
        units.put("mmol/mmol","millimole per millimole");
        units.put("mmol/mmol{urea}","millimole per millimole of urea");
        units.put("mmol/mmol{creat}","millimole per millmole of creatinine");
        units.put("mmol/min","millimole per minute");
        units.put("mmol/mol","millimole per mole");
        units.put("mmol/mol{creat}","millimole per mole of creatinine");
        units.put("mmol/s/L","millimole per second per liter");
        units.put("mmol/{specimen}","millimole per specimen");
        units.put("mmol/m2","millimole per square meter");
        units.put("mmol/{total_vol}","millimole per total volume");
        units.put("10*6","million");
        units.put("10*6.[CFU]/L","million colony forming unit per liter");
        units.put("10*6.[IU]","million international unit");
        units.put("10*6/(24.h)","million per 24 hour");
        units.put("10*6/kg","million per kilogram");
        units.put("10*6/L","million per liter");
        units.put("10*6/uL","million per microliter");
        units.put("10*6/mL","million per milliliter");
        units.put("mosm","milliosmole");
        units.put("mosm/kg","milliosmole per kilogram");
        units.put("mosm/L","milliosmole per liter");
        units.put("mPa","millipascal");
        units.put("mPa.s","millipascal second");
        units.put("ms","millisecond");
        units.put("mV","millivolt");
        units.put("mV/s","millivolt per second");
        units.put("{minidrop}/min","minidrop per minute");
        units.put("{minidrop}/s","minidrop per second");
        units.put("min","minute");
        units.put("min/d","minute per day");
        units.put("min/wk","minute per week");
        units.put("mol","mole");
        units.put("mol/m3","mole per cubic meter");
        units.put("mol/kg","mole per kilogram");
        units.put("mol/kg/s","mole per kilogram per second");
        units.put("mol/L","mole per liter");
        units.put("mol/mL","mole per milliliter");
        units.put("mol/mol","mole per mole");
        units.put("mol/s","mole per second");
        units.put("{#}/{platelet}","molecule per platelet");
        units.put("mo","month");
        units.put("{mm/dd/yyyy}","month-day-year");
        units.put("{M.o.M}","multiple of the median");
        units.put("{mutation}","mutation");
        units.put("nU/mL","nanoenzyme unit per milliliter");
        units.put("nU/{RBC}","nanoenzyme unit per red blood cell");
        units.put("ng","nanogram");
        units.put("ng{FEU}/mL","nanogram fibrinogen equivalent unit per milliliter ");
        units.put("ng/(24.h)","nanogram per 24 hour");
        units.put("ng/(8.h)","nanogram per 8 hour");
        units.put("ng/d","nanogram per day");
        units.put("ng/dL","nanogram per deciliter");
        units.put("ng/U","nanogram per enzyme unit");
        units.put("ng/g","nanogram per gram");
        units.put("ng/g{creat}","nanogram per gram of creatinine");
        units.put("ng/h","nanogram per hour");
        units.put("ng/kg","nanogram per kilogram");
        units.put("ng/kg/(8.h)","nanogram per kilogram per 8 hour");
        units.put("ng/kg/h","nanogram per kilogram per hour");
        units.put("ng/kg/min","nanogram per kilogram per minute");
        units.put("ng/L","nanogram per liter");
        units.put("ng/mg","nanogram per milligram");
        units.put("ng/mg{creat}","nanogram per milligram of creatinine");
        units.put("ng/mg{prot}","nanogram per milligram of protein");
        units.put("ng/mg/h","nanogram per milligram per hour");
        units.put("ng/mL{RBCs}","nanogram per milliliter of red blood cells");
        units.put("ng/mL/h","nanogram per milliliter per hour");
        units.put("ng/10*6","nanogram per million");
        units.put("ng/10*6{RBCs}","nanogram per million red blood cells");
        units.put("ng/mL","nanogram per millliiter");
        units.put("ng/min","nanogram per minute");
        units.put("ng/s","nanogram per second");
        units.put("ng/m2","nanogram per square meter");
        units.put("nkat","nanokatal");
        units.put("nL","nanoliter");
        units.put("nm","nanometer");
        units.put("nm/s/L","nanometer per second per liter");
        units.put("nmol","nanomole");
        units.put("nmol{BCE}","nanomole bone collagen equivalent");
        units.put("nmol{BCE}/L","nanomole bone collagen equivalent per liter");
        units.put("nmol/mmol{creat}","nanomole bone collagen equivalent per millimole of creatinine");
        units.put("nmol/mg{prot}","nanomole of 1/2 cystine per milligram of protein");
        units.put("nmol{ATP}","nanomole of ATP ");
        units.put("nmol/(24.h)","nanomole per 24 hour");
        units.put("nmol/d","nanomole per day");
        units.put("nmol/dL","nanomole per deciliter");
        units.put("nmol/dL{GF}","nanomole per deciliter of glomerular filtrate");
        units.put("nmol/g","nanomole per gram");
        units.put("nmol/g{creat}","nanomole per gram of creatinine");
        units.put("nmol/g{dry_wt}","nanomole per gram of dry weight");
        units.put("nmol/h/L","nanomole per hour per liter");
        units.put("nmol/h/mg{prot}","nanomole per hour per milligram of protein");
        units.put("nmol/h/mL","nanomole per hour per milliliter");
        units.put("nmol/L","nanomole per liter");
        units.put("nmol/L{RBCs}","nanomole per liter of red blood cells");
        units.put("nmol/L/mmol{creat}","nanomole per liter per millimole of creatinine");
        units.put("nmol/m/mg{prot}","nanomole per meter per milligram of protein");
        units.put("nmol/umol{creat}","nanomole per micromole  of creatinine");
        units.put("nmol/mg","nanomole per milligram");
        units.put("nmol/mg{creat}","nanomole per milligram of creatinine");
        units.put("nmol/mg{prot}","nanomole per milligram of protein");
        units.put("nmol/mg{prot}/h","nanomole per milligram of protein per hour");
        units.put("nmol/mg/h","nanomole per milligram per hour");
        units.put("nmol/mL","nanomole per milliliter");
        units.put("nmol/mL/h","nanomole per milliliter per hour");
        units.put("nmol/mL/min","nanomole per milliliter per minute");
        units.put("nmol/mmol","nanomole per millimole");
        units.put("nmol/mmol{creat}","nanomole per millimole of creatinine");
        units.put("nmol/min","nanomole per minute");
        units.put("nmol/min/mg{Hb}","nanomole per minute per milligram of hemoglobin");
        units.put("nmol/min/mg{prot}","nanomole per minute per milligram of protein");
        units.put("nmol/min/mg{protein}","nanomole per minute per milligram protein");
        units.put("nmol/min/mL","nanomole per minute per milliliter");
        units.put("nmol/min/10*6{cells}","nanomole per minute per million cells");
        units.put("nmol/mol","nanomole per mole");
        units.put("nmol/mol{creat}","nanomole per mole creatinine");
        units.put("nmol/nmol","nanomole per nanomole");
        units.put("nmol/s","nanomole per second");
        units.put("nmol/s/L","nanomole per second per liter");
        units.put("ns","nanosecond");
        units.put("N","Newton");
        units.put("N.cm","Newton centimeter");
        units.put("N.s","Newton second");
        units.put("{#}","number");
        units.put("{#}/a","number per annum (year)");
        units.put("{#}/d","number per day");
        units.put("{#}/g","number per gram");
        units.put("{#}/[HPF]","number per high power field");
        units.put("{#}/L","number per liter");
        units.put("{#}/[LPF]","number per low power field");
        units.put("{#}/uL","number per microliter");
        units.put("{#}/mL","number per milliliter");
        units.put("{#}/min","number per minute");
        units.put("{#}/wk","number per week");
        units.put("Ohm","Ohm");
        units.put("Ohm.m","Ohm meter");
        units.put("10*5","one hundred thousand");
        units.put("{OD_unit}","optical density unit");
        units.put("osm","osmole");
        units.put("osm/kg","osmole per kilogram");
        units.put("osm/L","osmole per liter");
        units.put("[oz_av]","ounce (US and British)");
        units.put("{Pan_Bio'U}","panbio unit");
        units.put("[ppb]","part per billion");
        units.put("[ppm]","part per million");
        units.put("[ppm]{v/v}","part per million in volume per volume");
        units.put("[ppth]","part per thousand");
        units.put("[pptr]","part per trillion");
        units.put("Pa","Pascal");
        units.put("/10*10","per 10 billion  ");
        units.put("/10*4{RBCs}","per 10 thousand red blood cells");
        units.put("/100","per 100");
        units.put("/100{cells}","per 100 cells");
        units.put("/100{neutrophils}","per 100 neutrophils");
        units.put("/100{spermatozoa}","per 100 spermatozoa");
        units.put("/100{WBCs}","per 100 white blood cells");
        units.put("/[arb'U]","per arbitrary unit");
        units.put("/10*9","per billion");
        units.put("/cm[H2O]","per centimeter of water");
        units.put("/m3","per cubic meter");
        units.put("/d","per day");
        units.put("/dL","per deciliter");
        units.put("/{entity}","per entity");
        units.put("/U","per enzyme unit");
        units.put("/g","per gram");
        units.put("/g{creat}","per gram of creatinine");
        units.put("/g{Hb}","per gram of hemoglobin");
        units.put("/g{tot_nit}","per gram of total nitrogen");
        units.put("/g{tot_prot}","per gram of total protein");
        units.put("/g{wet_tis}","per gram of wet tissue");
        units.put("/[HPF]","per high power field");
        units.put("/h","per hour");
        units.put("/[IU]","per international unit");
        units.put("/kg","per kilogram");
        units.put("/kg{body_wt}","per kilogram of body weight");
        units.put("/L","per liter");
        units.put("/[LPF]","per low power field");
        units.put("/uL","per microliter");
        units.put("/mg","per milligram");
        units.put("/mL","per milliliter");
        units.put("/mm","per millimeter");
        units.put("/mmol{creat}","per millimole of creatinine");
        units.put("/10*6","per million");
        units.put("/min","per minute");
        units.put("/mo","per month");
        units.put("/{OIF}","per oil immersion field");
        units.put("/s","per second");
        units.put("/m2","per square meter");
        units.put("/10*3","per thousand");
        units.put("/10*3{RBCs}","per thousand red blood cells");
        units.put("/10*12","per trillion ");
        units.put("/10*12{RBCs}","per trillion red blood cells");
        units.put("/(12.h)","per twelve hour");
        units.put("/wk","per week");
        units.put("/a","per year");
        units.put("%","percent");
        units.put("%{loss_AChR}","percent  loss of acetylcholine receptor");
        units.put("%{penetration}","percent  penetration");
        units.put("%{abnormal}","percent abnormal");
        units.put("%{activity}","percent activity");
        units.put("%{aggregation}","percent aggregation");
        units.put("%{at_60_min}","percent at 60 minute");
        units.put("%{basal_activity}","percent basal activity");
        units.put("%{binding}","percent binding");
        units.put("%{blockade}","percent blockade");
        units.put("%{blocked}","percent blocked");
        units.put("%{bound}","percent bound");
        units.put("%{breakdown}","percent breakdown");
        units.put("%{vol}","percent by volume");
        units.put("%{deficient}","percent deficient");
        units.put("%{dose}","percent dose");
        units.put("%{excretion}","percent excretion");
        units.put("%{Hb}","percent hemoglobin");
        units.put("%{hemolysis}","percent hemolysis");
        units.put("%{index}","percent index");
        units.put("%{inhibition}","percent inhibition");
        units.put("%{loss}","percent loss");
        units.put("%{lysis}","percent lysis");
        units.put("%{normal}","percent normal");
        units.put("%{pooled_plasma}","percent normal pooled plasma");
        units.put("%{bacteria}","percent of bacteria");
        units.put("%{baseline}","percent of baseline");
        units.put("%{cells}","percent of cells");
        units.put("%{RBCs}","percent of red blood cells");
        units.put("%{WBCs}","percent of white blood cells");
        units.put("%{positive}","percent positive");
        units.put("%{reactive}","percent reactive");
        units.put("%{recovery}","percent recovery");
        units.put("%{reference}","percent reference");
        units.put("%{residual}","percent residual");
        units.put("%{response}","percent response");
        units.put("%{saturation}","percent saturation");
        units.put("%{total}","percent total");
        units.put("%{uptake}","percent uptake");
        units.put("%{viable}","percent viable");
        units.put("{percentile}","percentile");
        units.put("[pH]","pH");
        units.put("{phenotype}","phenotype");
        units.put("pA","picoampere");
        units.put("pg","picogram");
        units.put("pg/{cell}","picogram per cell");
        units.put("pg/dL","picogram per deciliter");
        units.put("pg/L","picogram per liter");
        units.put("pg/mg","picogram per milligram");
        units.put("pg/mg{creat}","picogram per milligram of creatinine");
        units.put("pg/mL","picogram per milliliter");
        units.put("pg/mL{sLT}","picogram per milliliter sulfidoleukotrienes");
        units.put("pg/mm","picogram per millimeter");
        units.put("pg/{RBC}","picogram per red blood cell");
        units.put("pkat","picokatal");
        units.put("pL","picoliter");
        units.put("pm","picometer");
        units.put("pmol","picomole");
        units.put("pmol/(24.h)","picomole per 24 hour");
        units.put("pmol/d","picomole per day");
        units.put("pmol/dL","picomole per deciliter");
        units.put("pmol/g","picomole per gram");
        units.put("pmol/h/mg{prot}","picomole per hour per milligram of protein");
        units.put("pmol/H/mg{protein}","picomole per hour per milligram protein");
        units.put("pmol/h/mL","picomole per hour per milliliter ");
        units.put("pmol/L","picomole per liter");
        units.put("pmol/umol","picomole per micromole");
        units.put("pmol/umol{creat}","picomole per micromole of creatinine");
        units.put("pmol/mg{prot}","picomole per milligram of protein");
        units.put("pmol/mL","picomole per milliliter");
        units.put("pmol/mmol{creat}","picomole per millimole of creatinine");
        units.put("pmol/min","picomole per minute");
        units.put("pmol/min/mg{prot}","picomole per minute per milligram of protein");
        units.put("pmol/{RBC}","picomole per red blood cell");
        units.put("ps","picosecond");
        units.put("pT","picotesla");
        units.put("[pt_us]","pint (US)");
        units.put("[lb_av]","pound (US and British)");
        units.put("[psi]","pound per square inch");
        units.put("[qt_us]","quart (US)");
        units.put("{ratio}","ratio");
        units.put("{RBC}/uL","red blood cell per microliter");
        units.put("%{relative}","relative percent");
        units.put("{rel_saturation}","relative saturation");
        units.put("{risk}","risk");
        units.put("{Rubella_virus}","rubella virus");
        units.put("{saturation}","saturation");
        units.put("{score}","score");
        units.put("s","second");
        units.put("s/{control}","second per control");
        units.put("{shift}","shift");
        units.put("S","Siemens");
        units.put("Sv","Sievert");
        units.put("{s_co_ratio}","signal to cutoff ratio");
        units.put("{spermatozoa}/mL","spermatozoa per milliliter");
        units.put("cm2","square centimeter");
        units.put("cm2/s","square centimeter per second");
        units.put("dm2/s2","square decimeter per square second");
        units.put("[sft_i]","square foot (international)");
        units.put("[sin_i]","square inch (international)");
        units.put("m2","square meter");
        units.put("m2/s","square meter per second");
        units.put("mm2","square millimeter");
        units.put("[syd_i]","square yard (international)");
        units.put("{STDV}","standard deviation");
        units.put("{Tscore}","t score");
        units.put("[tbs_us]","tablespoon (US)");
        units.put("[tsp_us]","teaspoon (US)");
        units.put("T","Tesla");
        units.put("10*3","thousand");
        units.put("10*3{copies}/mL","thousand copies per milliliter");
        units.put("10*3/L","thousand per liter");
        units.put("10*3/uL","thousand per microliter");
        units.put("10*3/mL","thousand per milliliter");
        units.put("10*3{RBCs}","thousand red blood cells");
        units.put("{TSI_index}","thyroid-stimulating immunoglobulin index");
        units.put("{TmStp}","time stamp");
        units.put("{titer}","titer");
        units.put("[todd'U]","Todd unit");
        units.put("10*12/L","trillion per liter");
        units.put("[oz_tr]","Troy ounce");
        units.put("[tb'U]","tuberculin unit");
        units.put("V","volt");
        units.put("Wb","Weber");
        units.put("wk","week");
        units.put("{WBCs}","white blood cells");
        units.put("[yd_i]","yard (international)");
        units.put("a","year");
        units.put("{yyyy}","year");
        units.put("{Zscore}","z score");
    }

    public static Map<String, String> getMeasurementUnitsMap() {
        return units;
    }

}

