package uk.nhs.adaptors.connector.model;

import lombok.Getter;

@Getter
public enum MigrationStatus {
    REQUEST_RECEIVED,
    EHR_EXTRACT_REQUEST_ACCEPTED,
    EHR_EXTRACT_REQUEST_ERROR,
    EHR_EXTRACT_REQUEST_ACKNOWLEDGED,
    EHR_EXTRACT_REQUEST_NEGATIVE_ACK,
    EHR_EXTRACT_RECEIVED,
    EHR_EXTRACT_TRANSLATED,
    CONTINUE_REQUEST_ACCEPTED,
    CONTINUE_REQUEST_ERROR,
    MIGRATION_COMPLETED,
    ERROR
}
