FROM gradle:jdk17 AS build
COPY --chown=gradle:gradle ./gp2gp-translator /home/gradle/service
WORKDIR /home/gradle/service
RUN ./gradlew test --build-cache bootJar

FROM openjdk:17

EXPOSE 8085

RUN mkdir /app

COPY --from=build /home/gradle/service/build/libs/gp2gp-translator.jar /app/gp2gp-translator.jar

ENTRYPOINT ["java", "-cp", "/app/gp2gp-translator.jar", "-Dloader.main=Gp2gpTranslatorApplication", "org.springframework.boot.loader.PropertiesLauncher"]
