FROM gradle:jdk17 AS build
COPY --chown=gradle:gradle ./gpc-api-facade /home/gradle/service
WORKDIR /home/gradle/service
RUN ./gradlew test --build-cache bootJar

FROM openjdk:17

EXPOSE 8080

RUN mkdir /app

COPY --from=build /home/gradle/service/build/libs/gpc-api-facade.jar /app/gpc-api-facade.jar

ENTRYPOINT ["java", "-cp", "/app/gpc-api-facade.jar", "-Dloader.main=uk.nhs.adaptors.gpc.GpcFacadeApplication", "org.springframework.boot.loader.PropertiesLauncher"]
