echo "processing PWPT2"
node raw-compare.js "./unprocessed-files/provider-PWPT2-output.json" "./unprocessed-files/ps-PWPT2-output.json" "./raw-compare-results"
echo "processing PWPT3"
node raw-compare.js "./unprocessed-files/provider-PWPT3-output.json" "./unprocessed-files/ps-PWPT3-output.json" "./raw-compare-results"
echo "processing PWPT4"
node raw-compare.js "./unprocessed-files/provider-PWPT4-output.json" "./unprocessed-files/ps-PWPT4-output.json" "./raw-compare-results"
echo "processing PWPT5"
node raw-compare.js "./unprocessed-files/provider-PWPT5-output.json" "./unprocessed-files/ps-PWPT5-output.json" "./raw-compare-results"
echo "processing PWPT6"
node raw-compare.js "./unprocessed-files/provider-PWPT6-output.json" "./unprocessed-files/ps-PWPT6-output.json" "./raw-compare-results"
echo "processing PWPT7"
node raw-compare.js "./unprocessed-files/provider-PWPT7-output.json" "./unprocessed-files/ps-PWPT7-output.json" "./raw-compare-results"
echo "processing PWPT9"
node raw-compare.js "./unprocessed-files/provider-PWPT9-output.json" "./unprocessed-files/ps-PWPT9-output.json" "./raw-compare-results"
echo "processing PWPT10"
node raw-compare.js "./unprocessed-files/provider-PWPT10-output.json" "./unprocessed-files/ps-PWPT10-output.json" "./raw-compare-results"
echo "processing PWPT11"
node raw-compare.js "./unprocessed-files/provider-PWPT11-output.json" "./unprocessed-files/ps-PWPT11-output.json" "./raw-compare-results"