package uk.nhs.adaptors.gp2gpmhstestenv.mockspinemhsoutbound.model;

import lombok.Getter;

@Getter
public enum MigrationStatus {
    REQUEST_RECEIVED,
    EHR_EXTRACT_REQUEST_ACCEPTED,
    EHR_EXTRACT_REQUEST_ERROR,
    EHR_EXTRACT_REQUEST_ACKNOWLEDGED,
    EHR_EXTRACT_RECEIVED,
    EHR_EXTRACT_PROCESSING,
    EHR_EXTRACT_TRANSLATED,
    CONTINUE_REQUEST_ACCEPTED,
    CONTINUE_REQUEST_ERROR,
    MIGRATION_COMPLETED,
    ERROR_LRG_MSG_REASSEMBLY_FAILURE,
    ERROR_LRG_MSG_ATTACHMENTS_NOT_RECEIVED,
    ERROR_LRG_MSG_GENERAL_FAILURE,
    ERROR_LRG_MSG_TIMEOUT,
    ERROR_REQUEST_TIMEOUT,
    ERROR_EXTRACT_CANNOT_BE_PROCESSED,
    EHR_GENERAL_PROCESSING_ERROR,
    COPC_MESSAGE_RECEIVED,
    COPC_MESSAGE_PROCESSING,
    COPC_ACKNOWLEDGED,
    FINAL_ACK_SENT,
    EHR_EXTRACT_REQUEST_NEGATIVE_ACK_GP2GP_PATIENT_NOT_REGISTERED,
    EHR_EXTRACT_REQUEST_NEGATIVE_ACK_GP2GP_SENDER_NOT_CONFIGURED,
    EHR_EXTRACT_REQUEST_NEGATIVE_ACK_GP2GP_EHR_GENERATION_ERROR,
    EHR_EXTRACT_REQUEST_NEGATIVE_ACK_GP2GP_MISFORMED_REQUEST,
    EHR_EXTRACT_REQUEST_NEGATIVE_ACK_GP2GP_NOT_PRIMARY_HEALTHCARE_PROVIDER,
    EHR_EXTRACT_REQUEST_NEGATIVE_ACK_GP2GP_MULTI_OR_NO_RESPONSES,
    EHR_EXTRACT_REQUEST_NEGATIVE_ACK_UNKNOWN,
    EHR_EXTRACT_NEGATIVE_ACK_ABA_INCORRECT_PATIENT,
    EHR_EXTRACT_NEGATIVE_ACK_NON_ABA_INCORRECT_PATIENT,
    EHR_EXTRACT_NEGATIVE_ACK_FAILED_TO_INTEGRATE,
    EHR_EXTRACT_NEGATIVE_ACK_SUPPRESSED
}
